### ISSUE TITLE
console.log() in test is not working

### ISSUE THREAD

**Issue by frantic1048** [pine613/fly-ava#15]
I'm using fly-ava to run my AVA tests in my project. I found normal `console.log()` is not outputting log in terminal, while directly running `./node_modules/ava/cli.js` outputs log.

The actual situation is, my [PEG.js](https://github.com/pegjs/pegjs) parser's trace output, is not shown via fly-ava. [It uses `console.log()`](https://github.com/pegjs/pegjs/blob/266f17d11c772b6af334a6e2db63f71ce1b0fbf1/lib/compiler/passes/generate-js.js#L895), too. I have to run AVA separately to debug my PEG grammar. It's very painful to debug grammar without trace information.

Is there any idea to make log enabled?

**Comment by pine** [comment]
@frantic1048 Thank you reports.

I think it is problem. I'll fix it that.

**Comment by pine** [comment]
@frantic1048 Hello 😃 

I've just fixed that. Thanks!
