### ISSUE TITLE
Use programmatic API

### ISSUE THREAD

**Issue by sindresorhus** [pine613/fly-ava#4]
We've introduced a programmatic API. It's still not documented, as we want to be free to change it around, but would be nice to get some real world use of it.

You could look at how https://github.com/sindresorhus/ava/issues/345 gets implemented.

**Comment by sindresorhus** [comment]
Also, do a pull request linking this here: https://github.com/sindresorhus/ava#related ;)

**Comment by pine** [comment]
Thanks! I'll check later :smiley:

**Comment by pine** [comment]
@sindresorhus
I've just support ava programmatic API. Thank your issue report!
https://github.com/pine613/fly-ava/pull/5/files

**Comment by lukeed** [comment]
:raised_hands: hooray!

**Comment by pine** [comment]
:tada:
